name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26'

      - name: Test
        run: make test

      - name: Benchmark
        run: make bench

      - name: Coverage
        run: make coverage

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v4.0.1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          slug: jfallis/collatz
#          files: profile.cov
#          verbose: true

#      - name: Build
#        run: make build
